export interface Game {
  name: string;
  url: string;
}

function gameUrl(name: string): string {
  return `https://mightymath.centromariapolis.cl/app/${encodeURIComponent(name)}/`;
}

export const GAMES: Game[] = [
  { name: "Minecraft", url: gameUrl("Minecraft") },
  { name: "Monkey Mart", url: gameUrl("Monkey%20Mart") },
  { name: "Geometry Dash", url: gameUrl("Geometry%20Dash") },
  { name: "Cluster Rush", url: gameUrl("Cluster%20Rush") },
  { name: "BitLife", url: gameUrl("BitLife") },
  { name: "1v1 LOL", url: gameUrl("1v1%20LOL") },
  { name: "Bob the Robber 2", url: gameUrl("Bob%20the%20Robber%202") },
  { name: "Drift Boss", url: gameUrl("Drift%20Boss") },
  { name: "Basketball Stars", url: gameUrl("Basketball%20Stars") },
  { name: "Pixel Gun 3D", url: gameUrl("Pixel%20Gun%203D") },
  { name: "Basket Random", url: gameUrl("Basket%20Random") },
  { name: "Moto X3M", url: gameUrl("Moto%20X3M") },
  { name: "Death Run 3D", url: gameUrl("Death%20Run%203D") },
  { name: "Tactical Assassin 2", url: gameUrl("Tactical%20Assassin%202") },
  { name: "Friday Night Funkin", url: gameUrl("Friday%20Night%20Funkin") },
  {
    name: "Five Nights at Freddy's",
    url: gameUrl("Five%20Nights%20at%20Freddy's"),
  },
  { name: "Henry Stickmin", url: gameUrl("Henry%20Stickmin") },
  { name: "Slope", url: gameUrl("Slope") },
  { name: "Run 3", url: gameUrl("Run%203") },
  { name: "Subway Surfers", url: gameUrl("Subway%20Surfers") },
  { name: "Temple Run", url: gameUrl("Temple%20Run") },
  { name: "Snake", url: gameUrl("Snake") },
  { name: "Tetris", url: gameUrl("Tetris") },
  { name: "Pac-Man", url: gameUrl("Pac-Man") },
  { name: "Space Invaders", url: gameUrl("Space%20Invaders") },
  { name: "Flappy Bird", url: gameUrl("Flappy%20Bird") },
  { name: "Agar.io", url: gameUrl("Agar.io") },
  { name: "Slither.io", url: gameUrl("Slither.io") },
  { name: "Paper.io", url: gameUrl("Paper.io") },
  { name: "Krunker", url: gameUrl("Krunker") },
  { name: "Shell Shockers", url: gameUrl("Shell%20Shockers") },
  { name: "Bloons Tower Defense", url: gameUrl("Bloons%20Tower%20Defense") },
  { name: "Bloons TD 6", url: gameUrl("Bloons%20TD%206") },
  { name: "Among Us", url: gameUrl("Among%20Us") },
  { name: "Fall Guys", url: gameUrl("Fall%20Guys") },
  { name: "Happy Wheels", url: gameUrl("Happy%20Wheels") },
  { name: "Papa's Pizzeria", url: gameUrl("Papa's%20Pizzeria") },
  { name: "Papa's Burgeria", url: gameUrl("Papa's%20Burgeria") },
  { name: "Papa's Freezeria", url: gameUrl("Papa's%20Freezeria") },
  { name: "Papa's Sushiria", url: gameUrl("Papa's%20Sushiria") },
  { name: "Cookie Clicker", url: gameUrl("Cookie%20Clicker") },
  { name: "Idle Miner", url: gameUrl("Idle%20Miner") },
  { name: "Clicker Heroes", url: gameUrl("Clicker%20Heroes") },
  { name: "Rooftop Snipers", url: gameUrl("Rooftop%20Snipers") },
  { name: "Getaway Shootout", url: gameUrl("Getaway%20Shootout") },
  { name: "Fireboy and Watergirl", url: gameUrl("Fireboy%20and%20Watergirl") },
  {
    name: "Fireboy and Watergirl 2",
    url: gameUrl("Fireboy%20and%20Watergirl%202"),
  },
  { name: "Vex 3", url: gameUrl("Vex%203") },
  { name: "Vex 4", url: gameUrl("Vex%204") },
  { name: "Vex 5", url: gameUrl("Vex%205") },
  { name: "Parkour Race", url: gameUrl("Parkour%20Race") },
  { name: "Moto X3M 2", url: gameUrl("Moto%20X3M%202") },
  { name: "Moto X3M 3", url: gameUrl("Moto%20X3M%203") },
  { name: "Moto X3M 4", url: gameUrl("Moto%20X3M%204") },
  { name: "Moto X3M 5", url: gameUrl("Moto%20X3M%205") },
  { name: "Moto X3M Spooky Land", url: gameUrl("Moto%20X3M%20Spooky%20Land") },
  { name: "Moto X3M Pool Party", url: gameUrl("Moto%20X3M%20Pool%20Party") },
  { name: "Dirt Bike", url: gameUrl("Dirt%20Bike") },
  { name: "Burnout Drift", url: gameUrl("Burnout%20Drift") },
  { name: "Road Fury", url: gameUrl("Road%20Fury") },
  { name: "Traffic Rider", url: gameUrl("Traffic%20Rider") },
  { name: "Drive Mad", url: gameUrl("Drive%20Mad") },
  { name: "OvO", url: gameUrl("OvO") },
  { name: "Tomb of the Mask", url: gameUrl("Tomb%20of%20the%20Mask") },
  { name: "Crossy Road", url: gameUrl("Crossy%20Road") },
  { name: "Fancy Pants", url: gameUrl("Fancy%20Pants") },
  { name: "Potty Racers", url: gameUrl("Potty%20Racers") },
  { name: "Earn to Die", url: gameUrl("Earn%20to%20Die") },
  { name: "Earn to Die 2", url: gameUrl("Earn%20to%20Die%202") },
  { name: "Kick the Buddy", url: gameUrl("Kick%20the%20Buddy") },
  { name: "Jacksmith", url: gameUrl("Jacksmith") },
  { name: "Age of War", url: gameUrl("Age%20of%20War") },
  { name: "Age of War 2", url: gameUrl("Age%20of%20War%202") },
  { name: "Strike Force Heroes", url: gameUrl("Strike%20Force%20Heroes") },
  {
    name: "Strike Force Heroes 2",
    url: gameUrl("Strike%20Force%20Heroes%202"),
  },
  { name: "Super Smash Flash 2", url: gameUrl("Super%20Smash%20Flash%202") },
  { name: "Smash Karts", url: gameUrl("Smash%20Karts") },
  { name: "Bullet Force", url: gameUrl("Bullet%20Force") },
  { name: "Combat Reloaded", url: gameUrl("Combat%20Reloaded") },
  { name: "Combat Online", url: gameUrl("Combat%20Online") },
  { name: "Warbrokers", url: gameUrl("Warbrokers") },
  { name: "Zombs Royale", url: gameUrl("Zombs%20Royale") },
  { name: "Surviv.io", url: gameUrl("Surviv.io") },
  { name: "Yohoho.io", url: gameUrl("Yohoho.io") },
  { name: "Venge.io", url: gameUrl("Venge.io") },
  { name: "Crazy Cars", url: gameUrl("Crazy%20Cars") },
  { name: "Drift Hunters", url: gameUrl("Drift%20Hunters") },
  { name: "CarX Drift Racing", url: gameUrl("CarX%20Drift%20Racing") },
  { name: "Snow Rider", url: gameUrl("Snow%20Rider") },
  { name: "Bob the Robber", url: gameUrl("Bob%20the%20Robber") },
  { name: "Bob the Robber 3", url: gameUrl("Bob%20the%20Robber%203") },
  { name: "Bob the Robber 4", url: gameUrl("Bob%20the%20Robber%204") },
  { name: "Ninja Arashi", url: gameUrl("Ninja%20Arashi") },
  { name: "Stickman Hook", url: gameUrl("Stickman%20Hook") },
  { name: "Stickman Boost", url: gameUrl("Stickman%20Boost") },
  { name: "Angry Birds", url: gameUrl("Angry%20Birds") },
  { name: "Cut the Rope", url: gameUrl("Cut%20the%20Rope") },
  { name: "Where's My Water", url: gameUrl("Where's%20My%20Water") },
  { name: "Bad Piggies", url: gameUrl("Bad%20Piggies") },
  { name: "Plants vs Zombies", url: gameUrl("Plants%20vs%20Zombies") },
  { name: "Blossom Word Game", url: gameUrl("Blossom%20Word%20Game") },
  { name: "Wordle", url: gameUrl("Wordle") },
  { name: "2048", url: gameUrl("2048") },
  { name: "Threes", url: gameUrl("Threes") },
  { name: "Sudoku", url: gameUrl("Sudoku") },
  { name: "Mahjong", url: gameUrl("Mahjong") },
  { name: "Bubble Shooter", url: gameUrl("Bubble%20Shooter") },
  { name: "Jewel Quest", url: gameUrl("Jewel%20Quest") },
  { name: "Zuma", url: gameUrl("Zuma") },
  { name: "Bejeweled", url: gameUrl("Bejeweled") },
  { name: "Breakout", url: gameUrl("Breakout") },
  { name: "Pong", url: gameUrl("Pong") },
  { name: "Asteroids", url: gameUrl("Asteroids") },
  { name: "Frogger", url: gameUrl("Frogger") },
  { name: "Donkey Kong", url: gameUrl("Donkey%20Kong") },
  { name: "Super Mario", url: gameUrl("Super%20Mario") },
  { name: "Duck Hunt", url: gameUrl("Duck%20Hunt") },
  { name: "Mega Man", url: gameUrl("Mega%20Man") },
  { name: "Sonic", url: gameUrl("Sonic") },
  { name: "Kirby", url: gameUrl("Kirby") },
  { name: "Legend of Zelda", url: gameUrl("Legend%20of%20Zelda") },
  { name: "Metroid", url: gameUrl("Metroid") },
  { name: "Contra", url: gameUrl("Contra") },
  { name: "Castlevania", url: gameUrl("Castlevania") },
  { name: "Mega Man 2", url: gameUrl("Mega%20Man%202") },
  { name: "Double Dragon", url: gameUrl("Double%20Dragon") },
  { name: "Battletoads", url: gameUrl("Battletoads") },
  { name: "Punch Out", url: gameUrl("Punch%20Out") },
  { name: "Galaga", url: gameUrl("Galaga") },
  { name: "Dig Dug", url: gameUrl("Dig%20Dug") },
  { name: "Q-bert", url: gameUrl("Q-bert") },
  { name: "Centipede", url: gameUrl("Centipede") },
  { name: "Missile Command", url: gameUrl("Missile%20Command") },
  { name: "Joust", url: gameUrl("Joust") },
  { name: "Defender", url: gameUrl("Defender") },
  { name: "Robotron", url: gameUrl("Robotron") },
  { name: "Tempest", url: gameUrl("Tempest") },
  { name: "Tron", url: gameUrl("Tron") },
  { name: "Zaxxon", url: gameUrl("Zaxxon") },
  { name: "Burgertime", url: gameUrl("Burgertime") },
  { name: "Paperboy", url: gameUrl("Paperboy") },
  { name: "Dragon Ball Z", url: gameUrl("Dragon%20Ball%20Z") },
  { name: "Naruto", url: gameUrl("Naruto") },
  { name: "One Piece", url: gameUrl("One%20Piece") },
  { name: "Bleach", url: gameUrl("Bleach") },
  { name: "Attack on Titan", url: gameUrl("Attack%20on%20Titan") },
  { name: "My Hero Academia", url: gameUrl("My%20Hero%20Academia") },
  // Extra games to reach 150+
  { name: "Stickman Fighter", url: gameUrl("Stickman%20Fighter") },
  { name: "Robo Racing", url: gameUrl("Robo%20Racing") },
  { name: "Space Wars", url: gameUrl("Space%20Wars") },
  { name: "Tower Defense", url: gameUrl("Tower%20Defense") },
  { name: "Zombie Shooter", url: gameUrl("Zombie%20Shooter") },
  { name: "Dino Run", url: gameUrl("Dino%20Run") },
  { name: "Jetpack Joyride", url: gameUrl("Jetpack%20Joyride") },
  { name: "Fruit Ninja", url: gameUrl("Fruit%20Ninja") },
  { name: "Tiny Wings", url: gameUrl("Tiny%20Wings") },
  { name: "Bike Race", url: gameUrl("Bike%20Race") },
  { name: "Hill Climb Racing", url: gameUrl("Hill%20Climb%20Racing") },
  { name: "Extreme Car Driving", url: gameUrl("Extreme%20Car%20Driving") },
  { name: "Race Master 3D", url: gameUrl("Race%20Master%203D") },
  { name: "Turbo Dismount", url: gameUrl("Turbo%20Dismount") },
  { name: "Trials Frontier", url: gameUrl("Trials%20Frontier") },
  { name: "Ninja Jump", url: gameUrl("Ninja%20Jump") },
  { name: "Shadow Fighter", url: gameUrl("Shadow%20Fighter") },
  { name: "Bullet Rush", url: gameUrl("Bullet%20Rush") },
  { name: "Space Shooter", url: gameUrl("Space%20Shooter") },
  { name: "Alien Attack", url: gameUrl("Alien%20Attack") },
  { name: "Pirate Assault", url: gameUrl("Pirate%20Assault") },
  { name: "Castle Crashers", url: gameUrl("Castle%20Crashers") },
  { name: "Dungeon Quest", url: gameUrl("Dungeon%20Quest") },
  { name: "Fantasy War", url: gameUrl("Fantasy%20War") },
  { name: "Dragon Slayer", url: gameUrl("Dragon%20Slayer") },
  { name: "Sword Art Online", url: gameUrl("Sword%20Art%20Online") },
  { name: "Roblox", url: gameUrl("Roblox") },
  { name: "Fortnite", url: gameUrl("Fortnite") },
  { name: "Clash Royale", url: gameUrl("Clash%20Royale") },
  { name: "Clash of Clans", url: gameUrl("Clash%20of%20Clans") },
  { name: "Brawl Stars", url: gameUrl("Brawl%20Stars") },
  { name: "Mobile Legends", url: gameUrl("Mobile%20Legends") },
  { name: "Legends of Runeterra", url: gameUrl("Legends%20of%20Runeterra") },
  { name: "Chess", url: gameUrl("Chess") },
  { name: "Checkers", url: gameUrl("Checkers") },
  { name: "Solitaire", url: gameUrl("Solitaire") },
  { name: "Hearts", url: gameUrl("Hearts") },
  { name: "Spades", url: gameUrl("Spades") },
  { name: "Minesweeper", url: gameUrl("Minesweeper") },
  { name: "Pinball", url: gameUrl("Pinball") },
  { name: "Pool", url: gameUrl("Pool") },
  { name: "Air Hockey", url: gameUrl("Air%20Hockey") },
  { name: "Bowling", url: gameUrl("Bowling") },
  { name: "Mini Golf", url: gameUrl("Mini%20Golf") },
  { name: "Soccer Stars", url: gameUrl("Soccer%20Stars") },
  { name: "Football Legends", url: gameUrl("Football%20Legends") },
  { name: "Tennis Clash", url: gameUrl("Tennis%20Clash") },
  { name: "Baseball Pro", url: gameUrl("Baseball%20Pro") },
  { name: "Guitar Hero", url: gameUrl("Guitar%20Hero") },
  { name: "Piano Tiles", url: gameUrl("Piano%20Tiles") },
  { name: "Beat Saber", url: gameUrl("Beat%20Saber") },
  {
    name: "Dance Dance Revolution",
    url: gameUrl("Dance%20Dance%20Revolution"),
  },
  { name: "Osu!", url: gameUrl("Osu!") },
  { name: "Scary Maze", url: gameUrl("Scary%20Maze") },
  {
    name: "SCP Containment Breach",
    url: gameUrl("SCP%20Containment%20Breach"),
  },
  { name: "Slender Man", url: gameUrl("Slender%20Man") },
  {
    name: "Eyes: The Horror Game",
    url: gameUrl("Eyes%3A%20The%20Horror%20Game"),
  },
  { name: "Granny", url: gameUrl("Granny") },
];
